### ISSUE TITLE
Direct Messages are imported

### ISSUE THREAD

**Issue by ghost** [janboddez/import-from-mastodon#12]
There are options to ignore Boosts and Replies , but not Direct Messages.
I've tried deleting the posts created from a Direct Message but it gets recreated too.

**Comment by janboddez** [comment]
Good catch! I will fix this (but it may take a day or two).

There are a few possible workarounds (or you could temporarily disable the plugin, of course ...).

I think if you created a newer public status and import that, you could "safely" delete older DMs (the plugin should only ever [re-]import statuses that are newer than the most "recent" one---but if you deleted it again, you'd be back in the old situation).

(Using the ID of the so-called latest post is a bad way of limiting imports for other reasons, too, so I'm going to have to find something better.)

Not sure how familiar you are with modyifying WP, but, for now, you could try to add a little something like this to an mu-plugin or your theme's `functions.php`:
```
add_filter( 'import_from_mastodon_args', function( $args, $status ) {
  if ( isset( $status->visibility ) && 'public' !== $status->visibility ) {
    $args['post_status'] = 'private'; // Or 'draft';
  }
  return $args;
} );
```
That *should* stop these posts from being publicly visible.

**Update**: uncommented `post_status` assignment.

**Comment by janboddez** [comment]
Okay, so I think I've fixed this in version "0.3.0," i.e., the latest master (should rename this, still).

You should be able to re-download the ZIP file and install from there.

If you select the "public only" option, it will get only **public** toots. If you leave it disabled, it should **still** not include direct messages (although I've not explicitly tested this, yet), but it will (or rather, should) import followers-only and unlisted toots, too.

**Comment by janboddez** [comment]
Be great to hear your feedback.

**Comment by ghost** [comment]
Hey @janboddez , thanks for adding / fixing this issue too.
I am fairly new to Mastodon and hadn't even noticed the 'Post Privacy' options before!
Will disable 'Public Only' now and test it.
Mark.

**Comment by janboddez** [comment]
Seems to be working here.
