### ISSUE TITLE
Categories

### ISSUE THREAD

**Issue by ghost** [janboddez/import-from-mastodon#13]
I'd love to be able to set a Category for the incoming Toots as they currently all just get added to the default Uncategorized category.
It would be easy to find all my Toots then.

**Comment by janboddez** [comment]
Same remarks as here: https://github.com/janboddez/import-from-pixelfed/pull/6.

It's technically possible to set a post category, and I'm looking into adding it as a proper setting, but it **may** be incompatible with custom post types (for which taxonomies, like category, are not automatically set). In fact, CPTs might have completely **different** taxonomies.

I will probably simply remove the CPT setting (users "advanced" enough to be using CPTs will have to use a filter callback, then), and assume "normal" posts. And add a dropdown through which a single category can be set, which will then be applied for all imports.

The filter hook + a custom `functions.php` snippet can of course still be used to override the default behavior (to set more than one default category, for instance).

**Comment by janboddez** [comment]
Current version ("0.3.0," but I don't really do proper releases, at least not yet) contains the ability to select a post category. Also means I've for now removed the post type option.

(A custom post type can still be set [and the default category unset], should one wish to do so, using the `import_from_mastodon_args` hook.)

**Comment by ghost** [comment]
Working perfectly for me , Thank you!
