### ISSUE TITLE
Import favourites

### ISSUE THREAD

**Issue by diniscorreia** [janboddez/import-from-mastodon#17]
Hi there,

Any plans to support favourites?

**Comment by janboddez** [comment]
What would that look like, to you? Import other people's statuses (the ones you've favorited) as WordPress posts? (With a link back and the original author appended to it?) Or just a link?

I mean, the authors of these statuses are obviously not going to be the “authors/users” known to your WordPress install, so I'm assuming you see this more as a sort of bookmarking tool (like Delicious, etc., in the past).

**Comment by diniscorreia** [comment]
I was thinking of just a link, not necessarily the whole toot (this would still be a WP post by the site author).

Was looking at [Indieweb examples of 'like'](https://indieweb.org/like) and this was what I had in mind. There are a couple of folks storing their likes/faves, not only on toots/tweets but from other indieweb sites as well ([Ryan Barrett](https://snarfed.org/2014-02-04_re-today-is-the-last-day-of-luckily-can-be-used-as-a-replacement) for example just stores a link, although I think the text could be a lot more descriptive; [Aaron Parecki](https://aaronparecki.com/likes) apparently import the liked content, but this seems overkill to me).

**Comment by janboddez** [comment]
OK, clear. I have likes on my site, but I don't PESOS (or even POSSE) them; they're purely a "direct webmention" thing.

Not sure how I would add this functionality to this particular plugin; it could be a separate add-on plugin, for instance, that uses the same settings (i.e., the same auth token and so on).

In fact all you'd need is a second API call to a slightly different URL (and of course parse and process the results a tiny bit differently). I _could_ add that behind a "flag" of sorts, i.e., a filter hook that'd ensure the code is run only with the right one liner in, e.g., `functions.php`.

**Comment by diniscorreia** [comment]
Out of curiosity: was just checking your site, how are you storing those bookmarks on your stream?

**Comment by janboddez** [comment]
I mostly use a Micropub client (Indigenous/IndiePass for Android) to add/bookmark URLs to my site. I have a couple filters in place that mark them up with microformats and parse Markdown (which I use to indicate blockquotes etc.).

Sometimes, I'll write HTML by hand instead (in WP Admin on the desktop). I'm experimenting with Gutenberg blocks (https://github.com/janboddez/indieblocks) on a couple other sites, but not on this one (yet).

**Comment by janboddez** [comment]
I.e., they're just "posts" (I use a CPT for all my notes, not just bookmarks, hence the quotes); I don't use special taxonomies or anything. The microformats are what "makes" them bookmarks. But I suppose you were asking about how I create them, :-) so, yeah, mostly through Micropub.

**Comment by diniscorreia** [comment]
Ok, leaving this here in case anyone stumbles on the issue looking for the same – [here's the fork with favourites support](https://github.com/diniscorreia/import-from-mastodon).

**Comment by janboddez** [comment]
Cool. I might eventually (distant future, probably :-P) add favorites as an option that is disabled by default; now I know where to go look for inspiration.
